name: xdslmt
description: xDSL Monitoring tool is an android app for collect and analyze DSL line stats in realtime and background.
publish_to: 'none'
version: 2.0.2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  equatable: ^2.0.5
  csv: ^5.1.1
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  crypto: ^3.0.3
  logging: ^1.2.0
  # device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.12.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
